# Generated by Django 5.2.1 on 2025-05-09 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_community_event_community'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ButterflyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='ชื่อประเภทผีเสื้อ')),
                ('slug', models.SlugField(blank=True, help_text='สร้างอัตโนมัติจากชื่อ (ภาษาอังกฤษ) ถ้าเว้นว่าง', max_length=120, unique=True)),
                ('description', models.TextField(verbose_name='คำอธิบายลักษณะ')),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='butterfly_type_icons/', verbose_name='รูปไอคอนประจำประเภท')),
                ('theme_colors_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='สี/ธีมที่สื่อถึง')),
            ],
            options={
                'verbose_name': 'ประเภทผีเสื้อ',
                'verbose_name_plural': '01. ประเภทผีเสื้อ',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='ข้อความคำถาม')),
                ('order', models.PositiveIntegerField(default=0, help_text='ลำดับการแสดงผลของคำถาม (เลขน้อยแสดงก่อน)', verbose_name='ลำดับ')),
            ],
            options={
                'verbose_name': 'คำถาม Quiz',
                'verbose_name_plural': '02. คำถาม Quiz',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='community',
            options={'ordering': ['name'], 'verbose_name_plural': 'Communities'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date', '-time']},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'โปรไฟล์ผู้ใช้', 'verbose_name_plural': '04. โปรไฟล์ผู้ใช้'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='quiz_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='วันที่ทำ Quiz เสร็จสิ้น'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_in_category', to='myapp.category'),
        ),
        migrations.AlterField(
            model_name='event',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_in_community', to='myapp.community'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='เกี่ยวกับฉัน'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='รูปโปรไฟล์'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='assigned_butterfly_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_of_this_type', to='myapp.butterflytype', verbose_name='ประเภทผีเสื้อที่ได้รับ'),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='ข้อความตัวเลือก')),
                ('points_to_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defining_choices', to='myapp.butterflytype', verbose_name='ให้คะแนนแก่ประเภทผีเสื้อ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='myapp.question', verbose_name='ของคำถาม')),
            ],
            options={
                'verbose_name': 'ตัวเลือกคำตอบ Quiz',
                'verbose_name_plural': '03. ตัวเลือกคำตอบ Quiz',
            },
        ),
    ]
