# Generated by Django 5.2.1 on 2025-05-10 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_butterflytype_question_alter_attendance_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-created_at'], 'verbose_name': 'การเข้าร่วมกิจกรรม', 'verbose_name_plural': '08. การเข้าร่วมกิจกรรม'},
        ),
        migrations.AlterModelOptions(
            name='butterflytype',
            options={'ordering': ['name'], 'verbose_name': 'ประเภทผีเสื้อ', 'verbose_name_plural': '01. ประเภทผีเสื้อ (Quiz)'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'หมวดหมู่กิจกรรม', 'verbose_name_plural': '06. หมวดหมู่กิจกรรม'},
        ),
        migrations.AlterModelOptions(
            name='community',
            options={'ordering': ['name'], 'verbose_name': 'ชุมชน', 'verbose_name_plural': '05. ชุมชน'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date', '-time'], 'verbose_name': 'กิจกรรม', 'verbose_name_plural': '07. กิจกรรม'},
        ),
        migrations.AddField(
            model_name='butterflytype',
            name='long_description',
            field=models.TextField(blank=True, null=True, verbose_name='คำอธิบายแบบยาว (แสดงใน Quiz Result)'),
        ),
        migrations.AddField(
            model_name='butterflytype',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ชื่อประเภท (ภาษาอังกฤษสำหรับ Slug)'),
        ),
        migrations.AddField(
            model_name='butterflytype',
            name='result_image',
            field=models.ImageField(blank=True, null=True, upload_to='butterfly_results/', verbose_name='รูปภาพผลลัพธ์หลัก (แสดงใน Quiz Result)'),
        ),
        migrations.AddField(
            model_name='butterflytype',
            name='strengths',
            field=models.TextField(blank=True, null=True, verbose_name='จุดแข็ง (แสดงใน Quiz Result)'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='วันที่บันทึกสถานะ'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='myapp.event', verbose_name='กิจกรรม'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('attending', 'เข้าร่วม'), ('interested', 'สนใจ'), ('not_attending', 'ไม่เข้าร่วม')], default='attending', max_length=20, verbose_name='สถานะ'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_attendances', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้'),
        ),
        migrations.AlterField(
            model_name='butterflytype',
            name='description',
            field=models.TextField(verbose_name='คำอธิบายสั้นๆ (แสดงใน Quiz Result)'),
        ),
        migrations.AlterField(
            model_name='butterflytype',
            name='icon_image',
            field=models.ImageField(blank=True, null=True, upload_to='butterfly_type_icons/', verbose_name='รูปไอคอน (แสดงทั่วไป)'),
        ),
        migrations.AlterField(
            model_name='butterflytype',
            name='slug',
            field=models.SlugField(blank=True, help_text='สร้างอัตโนมัติจากชื่อภาษาอังกฤษ ถ้าเว้นว่าง', max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='butterflytype',
            name='theme_colors_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='สี/ธีมที่สื่อถึง (คำอธิบาย)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='รูปภาพหมวดหมู่'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='ชื่อหมวดหมู่'),
        ),
        migrations.AlterField(
            model_name='community',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='รายละเอียด'),
        ),
        migrations.AlterField(
            model_name='community',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='communities/', verbose_name='รูปภาพชุมชน'),
        ),
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ชื่อชุมชน'),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_in_category', to='myapp.category', verbose_name='หมวดหมู่'),
        ),
        migrations.AlterField(
            model_name='event',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_in_community', to='myapp.community', verbose_name='จัดโดยชุมชน (ถ้ามี)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(verbose_name='วันที่จัดกิจกรรม'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(verbose_name='รายละเอียดกิจกรรม'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='รูปภาพกิจกรรม'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=200, verbose_name='สถานที่จัดกิจกรรม'),
        ),
        migrations.AlterField(
            model_name='event',
            name='max_attendees',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='จำนวนผู้เข้าร่วมสูงสุด (ถ้ามี)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL, verbose_name='ผู้จัดกิจกรรม'),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(verbose_name='เวลาเริ่มกิจกรรม'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200, verbose_name='ชื่อกิจกรรม'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profiles/default_avatar.png', null=True, upload_to='profiles/', verbose_name='รูปโปรไฟล์'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้'),
        ),
    ]
