# Generated by Django 5.2.1 on 2025-05-11 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_attendance_options_alter_butterflytype_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='butterflytype',
            name='text_color',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Tailwind Text Color (เช่น purple-700)'),
        ),
        migrations.AddField(
            model_name='butterflytype',
            name='theme_color_end',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Tailwind BG Gradient To (เช่น pink-50)'),
        ),
        migrations.AddField(
            model_name='butterflytype',
            name='theme_color_start',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Tailwind BG Gradient From (เช่น purple-50)'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('attending', 'เข้าร่วม'), ('interested', 'สนใจ'), ('not_attending', 'ไม่เข้าร่วม')], default='interested', max_length=20, verbose_name='สถานะ'),
        ),
        migrations.AlterField(
            model_name='butterflytype',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='ชื่อประเภทผีเสื้อ (ไทย)'),
        ),
        migrations.AlterField(
            model_name='butterflytype',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ชื่อประเภท (อังกฤษสำหรับ Slug)'),
        ),
        migrations.AlterField(
            model_name='butterflytype',
            name='slug',
            field=models.SlugField(blank=True, help_text='สร้างอัตโนมัติจากชื่อภาษาอังกฤษ (ถ้ามี) หรือชื่อภาษาไทย', max_length=120, unique=True),
        ),
    ]
