# Generated by Django 5.2.1 on 2025-05-27 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_populate_quiz_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_pro_member',
            field=models.BooleanField(default=False, verbose_name='เป็นสมาชิกโปร'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pro_membership_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='วันที่หมดอายุสมาชิกโปร'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pro_membership_start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='วันที่เริ่มสมาชิกโปร'),
        ),
    ]
